name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  NODE_OPTIONS: '--max-old-space-size=4096'

  BUILD: 'true'
  WORKING_DIRECTORY: '.'
  WEBVIEW2: 'browser'

jobs:
  build:
    runs-on:  'ubuntu-22.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Setup and configure GoLang
      - name: Setup GoLang
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: '1.23'
      - run: go version
        shell: bash

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Setup and configure NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: './frontend/pnpm-lock.yaml'

      # install Wails
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        shell: bash
      - name: Update Ubuntu package list
        if: runner.os == 'Linux'
        run: sudo apt-get update
        shell: bash
      - name: Install Ubuntu Wails deps
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgtk-3-0 libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu

      # Building step
      - name: Build App
        if: runner.os == 'Linux'
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          wails build --platform ${{ matrix.build.platform }} -webview2 ${{ env.WEBVIEW2 }} -o ${{ matrix.build.name }}-webkit2-40 -tags webkit2_40
          wails build --platform ${{ matrix.build.platform }} -webview2 ${{ env.WEBVIEW2 }} -o ${{ matrix.build.name }}-webkit2-41 -tags webkit2_41
        shell: bash
