name: Wails build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  discussions: write

env:
  NODE_OPTIONS: '--max-old-space-size=4096'

  BUILD: 'true'
  WORKING_DIRECTORY: '.'
  WEBVIEW2: 'browser'

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'spinup-app'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          # - name: 'spinup-app'
          #   platform:  'windows/amd64'
          #   os: 'windows-latest'
          # - name: 'spinup-app'
          #   platform:  'darwin/universal'
          #   os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # - name: Build wails
      #   uses: dAppServer/wails-build-action@v2.2
      #   id: build
      #   with:
      #     wails-build-webview2: embed

      # Setup and configure GoLang
      - name: Setup GoLang
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: '1.23'
      - run: go version
        shell: bash
      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        working-directory: ${{ env.WORKING_DIRECTORY }}/frontend
        with:
          version: 9
      # Setup and configure NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      # install wails
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        shell: bash
      - name: Install Ubuntu Wails deps
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu
        shell: bash
      - name: Install macOS Wails deps
        if: runner.os == 'macOS'
        run: brew install mitchellh/gon/gon
        shell: bash
      # Building step
      - name: Build macOs App
        if: runner.os == 'macOS'
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: wails build --platform ${{ matrix.build.platform }} -webview2 ${{ env.WEBVIEW2 }} -o ${{ matrix.build.name }}
        shell: bash
      - name: Build Linux App
        if: runner.os == 'Linux'
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: wails build --platform ${{ matrix.build.platform }} -webview2 ${{ env.WEBVIEW2 }} -o ${{ matrix.build.name }} -tags webkit2_41
        shell: bash
      # - name: Build Windows App
      #   if: runner.os == 'Windows' && inputs.nsis == 'false'
      #   working-directory: ${{ env.WORKING_DIRECTORY }}
      #   run: wails build --platform ${{ matrix.build.platform }} -webview2 ${{ env.WEBVIEW2 }} -o ${{ matrix.build.name }}
      #   shell: bash
      # - name: Build Windows App + Installer
      #   if: runner.os == 'Windows' && inputs.nsis == 'true'
      #   working-directory: ${{ env.WORKING_DIRECTORY }}
      #   run: wails build --platform ${{ matrix.build.platform }} -webview2 ${{ env.WEBVIEW2 }} -nsis -o ${{ matrix.build.name }}
      #   shell: bash
      # - name: Add macOS perms
      #   if: runner.os == 'macOS'
      #   working-directory: ${{ env.WORKING_DIRECTORY }}
      #   run: chmod +x build/bin/*/Contents/MacOS/*
      #   shell: bash
      - name: Add Linux perms
        if: runner.os == 'Linux'
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: chmod +x build/bin/*
        shell: bash

      # Package as .deb for Ubuntu
      - name: Package as .deb
        if: runner.os == 'Linux'
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          VERSION: ${{ github.ref }}
        run: |
          mkdir -p deb/spinup-app/DEBIAN
          mkdir -p deb/spinup-app/usr/local/bin &&
          cp build/bin/spinup-app deb/spinup-app/usr/local/bin/spinup-app &&

          echo "Package: spinup-app" > deb/spinup-app/DEBIAN/control
          echo "Version: ${VERSION/v/""}" >> deb/spinup-app/DEBIAN/control
          echo "Section: base" >> deb/spinup-app/DEBIAN/control
          echo "Priority: optional" >> deb/spinup-app/DEBIAN/control
          echo "Architecture: amd64" >> deb/spinup-app/DEBIAN/control
          echo "Depends: libgtk-3-0, libwebkit2gtk-4.1-dev" >> deb/spinup-app/DEBIAN/control
          echo "Maintainer: iskandervdh" >> deb/spinup-app/DEBIAN/control
          echo "Description: Quickly spin up your multi command projects." >> deb/spinup-app/DEBIAN/control

          dpkg-deb --build deb/spinup-app
        shell: bash

      # Upload build assets
      - uses: actions/upload-artifact@v3
        with:
          name: Wails Build ${{ runner.os }} ${{ matrix.build.name }}
          path: |
            */bin/
            *\bin\*
            deb/spinup-app.deb
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            */bin/*
            deb/spinup-app.deb
