name: Wails build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  discussions: write

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'spinup-app'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          # - name: 'spinup-app'
          #   platform:  'windows/amd64'
          #   os: 'windows-latest'
          # - name: 'spinup-app'
          #   platform:  'darwin/universal'
          #   os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install webkitgtk-4.1
        if: os.runner == 'Linux'
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.1-dev

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          wails-build-webview2: embed
          go-version: '1.23'
          node-version: '22.x'
